version: '3.7'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "19876:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "13654:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
      - "55681:55681"
      - "4317:4317"

  prometheus-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: prometheus
      POSTGRES_PASSWORD: prometheus
      POSTGRES_DB: prometheus

  grafana-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: grafana
      MYSQL_DATABASE: grafana
      MYSQL_USER: grafana
      MYSQL_PASSWORD: grafana

volumes:
  grafana-storage: