version: '3.7'

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    container_name: otel-collector
    volumes:
      - ./otelcol/config.yaml:/etc/otelcol-contrib/config.yaml
    command:
      - '--config'
      - '/etc/otelcol-contrib/config.yaml'
    ports:
      - 4317:4317
      - 8889:8889
    depends_on:
      - jaeger
    networks:
      - monitoring-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./.docker/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 19876:9090
    networks:
      - monitoring-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./.docker/grafana:/var/lib/grafana
    ports:
      - 13654:3000
    networks:
      - monitoring-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "6831:6831/udp" # UDP port for Jaeger agent
      - "16686:16686" # Web UI
      - "14268:14268" # HTTP port for spans
    networks:
      - monitoring-network

networks:
  monitoring-network: